import { v4 as uuid } from "uuid";

export const products = [
  {
    _id: uuid(),
    name: "Broccoli Vegetables",
    original_price: 9,
    discounted_price: 7,
    category_name: "Vegetable", // Added category
    is_stock: false,
    rating: 4.3,
    reviews: 109,
    trending: true,
    size: 5,
    img: "/assets/images/products-images/broccoli-vegetable8.png",
  },
  {
    _id: uuid(),
    name: "Carrot Vegetables",
    original_price: 9,
    discounted_price: 7,
    category_name: "Vegetable", // Added category
    is_stock: true,
    rating: 4.1,
    reviews: 129,
    size: 7,
    img: "/assets/images/products-images/carrot.png",
  },
  {
    _id: uuid(),
    name: "Bok Choy Vegetable",
    original_price: 13,
    discounted_price: 7,
    category_name: "Vegetable", // Changed category
    is_stock: true,
    rating: 2.7,
    reviews: 19,
    trending: false,
    size: 4,
    img: "/assets/images/products-images/bok-choy-vegetable.png",
  },
  {
    _id: uuid(),
    name: "Eggplant Vegetable",
    original_price: 8,
    discounted_price: 5,
    category_name: "Vegetable", // Added category
    is_stock: true,
    rating: 4.5,
    reviews: 109,
    size: 7,
    img: "/assets/images/products-images/eggplant-vegetable.png",
  },
  {
    _id: uuid(),
    name: "Garlic Vegetable",
    original_price: 10,
    discounted_price: 8,
    category_name: "Vegetable", // Added category
    is_stock: true,
    rating: 3.4,
    reviews: 39,
    size: 5,
    img: "/assets/images/products-images/gralic-vegetable11.png",
  },
  {
    _id: uuid(),
    name: "Tomato Vegetable",
    original_price: 13,
    discounted_price: 10,
    category_name: "Vegetable", // Added category
    is_stock: true,
    rating: 3.6,
    reviews: 32,
    size: 5,
    img: "/assets/images/products-images/tomato-vegetable24.png",
  },
  {
    _id: uuid(),
    name: "Passion Fruit",
    original_price: 15,
    discounted_price: 11,
    category_name: "Fruit", // Added category
    is_stock: true,
    rating: 4.6,
    reviews: 1094,
    size: 7,
    img: "/assets/images/products-images/passion-fruite.png",
  },
  {
    _id: uuid(),
    name: "Red Pepper Vegetable",
    original_price: 18,
    discounted_price: 13,
    category_name: "Vegetable", // Added category
    is_stock: true,
    rating: 4.5,
    reviews: 166,
    trending: false,
    size: 7,
    img: "/assets/images/products-images/red-pepper-vegetable21.png",
  },
  {
    _id: uuid(),
    name: "Kiwi Fruit",
    original_price: 14,
    discounted_price: 10,
    category_name: "Fruit", // Added category
    is_stock: true,
    rating: 4.6,
    reviews: 47,
    trending: false,
    size: 10,
    img: "/assets/images/products-images/kiwi.png",
  },
  {
    _id: uuid(),
    name: "Papaya Fruit",
    original_price: 13,
    discounted_price: 0,
    category_name: "Fruit", // Added category
    is_stock: true,
    rating: 4.5,
    reviews: 200,
    trending: false,
    size: 9,
    img: "/assets/images/products-images/papaya-fruite.png",
  },
  {
    _id: uuid(),
    name: "Pomegranate Fruit",
    original_price: 9,
    discounted_price: 7,
    category_name: "Fruit", // Added category
    is_stock: true,
    rating: 4.0,
    reviews: 222,
    trending: false,
    size: 6,
    img: "/assets/images/products-images/pomegranate-fruits.png",
  },
  {
    _id: uuid(),
    name: "Strawberries Fruits",
    original_price: 12,
    discounted_price: 9,
    category_name: "Fruit", // Added category
    is_stock: false,
    rating: 3.1,
    reviews: 29, 
    trending: true,
    size: 6,
    img: "/assets/images/products-images/strawberries-fruits.png",
  },
  {
    _id: uuid(),
    name: "Turkey Wing Meat",
    original_price: 14,
    discounted_price: 10,
    category_name: "Meat", // Added category
    is_stock: true,
    rating: 2.3,
    reviews: 25,
    trending: false,
    size: 7,
    img: "/assets/images/products-images/turkey-wing-meat.png",
  },
  {
    _id: uuid(),
    name: "Pork Meat",
    original_price: 9,
    discounted_price: 7,
    category_name: "Meat", // Added category
    is_stock: false,
    rating: 1.7,
    reviews: 14,
    trending: false,
    size: 8,
    img: "/assets/images/products-images/pork-meat-img.png",
  },
  {
    _id: uuid(),
    name: "Pepperoni Meat",
    original_price: 20,
    discounted_price: 15,
    category_name: "Meat", // Added category
    is_stock: true,
    rating: 4.3,
    reviews: 144,
    trending: false,
    size: 9,
    img: "/assets/images/products-images/peperoni-meat.png",
  },
  {
    _id: uuid(),
    name: "Parma Ham Meat",
    original_price: 35,
    discounted_price: 32,
    category_name: "Meat", // Added category
    is_stock: false,
    rating: 4.2,
    reviews: 89,
    size: 9,
    img: "/assets/images/products-images/parma-ham-meat.png",
  },
  {
    _id: uuid(),
    name: "Bitter Gourd",
    original_price: 12,
    discounted_price: 11,
    category_name: "Vegetable", // Added category
    is_stock: false,
    rating: 4.9,
    reviews: 398,
    trending: false,
    size: 6,
    img: "/assets/images/products-images/bitter-gourd-vegetable.png",
  },
  {
    _id: uuid(),
    name: "Cauliflower Vegetable",
    original_price: 13.99,
    discounted_price: 9.99,
    category_name: "Vegetable", // Added category
    is_stock: true,
    rating: 4.9,
    reviews: 528,
    trending: true,
    size: "Large",
    img: "/assets/images/products-images/cauliflower-vegetable.png",
    restaurant: {
      name: "Café Chiet (Behind Royal Palace)",
      type: "Tea & Coffee",
      delivery_time: "10-25 min",
      delivery_fee: 0.99,
    },
  },
  {
    _id: uuid(),
    name: "Coriander Vegetable",
    original_price: 9,
    discounted_price: 6,
    category_name: "Vegetable", // Added category
    is_stock: true,
    rating: 4.4,
    reviews: 19,
    size: 6,
    img: "/assets/images/products-images/coriander-vegetable.png",
  },
  {
    _id: uuid(),
    name: "Asparagus Vegetable",
    original_price: 14,
    discounted_price: 9,
    category_name: "Vegetable", // Added category
    is_stock: false,
    rating: 4.3,
    reviews: 132,
    size: 7,
    img: "/assets/images/products-images/asparagus-vegetable7.png",
  },
  {
    _id: uuid(),
    name: "Pumpkin Vegetable",
    original_price: 13,
    discounted_price: 10,
    category_name: "Vegetable", // Added category
    is_stock: true,
    rating: 5.0,
    reviews: 132,
    trending: true,
    size: 7,
    img: "/assets/images/products-images/pumpkin-vegetable23.png",
  },
  {
    _id: uuid(),
    name: "Pea Vegetable",
    original_price: 12,
    discounted_price: 10,
    category_name: "Vegetable", // Added category
    is_stock: false,
    rating: 4.8,
    reviews: 654,
    trending: true,
    size: 8,
    img: "/assets/images/products-images/pea-vegetable19.png",
  },
  {
    _id: uuid(),
    name: "Red Cabbage Vegetable",
    original_price: 14,
    discounted_price: 10,
    category_name: "Vegetable", // Added category
    is_stock: true,
    rating: 3.9,
    reviews: 65,
    trending: false,
    size: 9,
    img: "/assets/images/products-images/red-cabbage-vegetable22.png",
  },
  {
    _id: uuid(),
    name: "Meat",
    original_price: 43,
    discounted_price: 37,
    category_name: "Meat", // Added category
    is_stock: true,
    rating: 3.5,
    reviews: 43,
    trending: false,
    size: 7,
    img: "/assets/images/products-images/meat1.png",
  },
];